from pathlib import Path


def write(path, content):
    Path(path).write_text(content, encoding='utf-8')


# The loader boundary no longer needs to name the retired compatibility file or
# symbol; canonical vocabulary governance owns the absence check.
loader_path = Path('tests/architecture/content-loading-boundary.test.js')
loader = loader_path.read_text(encoding='utf-8')
start = loader.index("  it('the retired compatibility registry is absent'")
end = loader.index("  })", start) + len("  })")
loader = loader[:start] + "  it('has no second loader registry definition', () => {\n    const registryPath = resolve(root, 'src/content/chapterContentRegistry.js')\n    const definitions = allSrcFiles.filter(file =>\n      file !== registryPath && /(?:export\\s+)?const\\s+CHAPTER_CONTENT_LOADERS\\s*=/.test(readFileSync(file, 'utf8'))\n    )\n    expect(definitions).toHaveLength(0)\n  })" + loader[end:]
write(loader_path, loader)

# Literal-token checks are easier to audit than regexes here and cannot acquire
# hidden control characters while being generated by Python.
write('tests/architecture/canonical-content-vocabulary.test.js', r"""import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'

const root = resolve(process.cwd())
const activeRoots = [
  'src', 'tests', 'docs/system', 'docs/components', 'docs/workflows',
  'docs/canonical', 'docs/content', '.claude/skills',
]
const activeFiles = ['CLAUDE.md', 'COMPONENTS.md']
const skipped = new Set(['archive', 'superpowers', 'node_modules', 'dist', 'coverage'])
const self = 'tests/architecture/canonical-content-vocabulary.test.js'

function walk(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) return skipped.has(entry.name) ? [] : walk(path)
    return /\.(js|jsx|mjs|md|sh|json)$/.test(entry.name) ? [path] : []
  })
}

const files = [
  ...activeRoots.flatMap(path => walk(resolve(root, path))),
  ...activeFiles.map(path => resolve(root, path)).filter(existsSync),
].map(path => ({
  path: relative(root, path).replaceAll('\\', '/'),
  content: readFileSync(path, 'utf8'),
})).filter(file => file.path !== self)

function tokenOffenders(tokens, allowedPaths = []) {
  const allowed = new Set(allowedPaths)
  return files
    .filter(file => !allowed.has(file.path) && tokens.some(token => file.content.includes(token)))
    .map(file => file.path)
    .sort()
}

describe('canonical content vocabulary', () => {
  it('removes completed compatibility files and authoring paths', () => {
    for (const path of [
      'src/modules.js',
      'src/components/layout/ModulePlayer.jsx',
      'src/app/moduleNavigation.js',
      'src/content/moduleContentRegistry.js',
      'src/data/tagModuleMap.js',
      '.claude/skills/module-creation',
    ]) expect(existsSync(resolve(root, path)), path).toBe(false)
    expect(existsSync(resolve(root, '.claude/skills/chapter-creation/SKILL.md'))).toBe(true)
  })

  it('blocks legacy runtime, registry and progress APIs from active surfaces', () => {
    expect(tokenOffenders([
      'ModulePlayer', 'moduleNavigation', 'MODULE_CONTENT_LOADERS', 'TAG_MODULE_MAP',
      'MODULE_GROUPS', 'getModuleState', 'saveModuleState', 'getModulePct',
      'getContinueModule', 'getInProgressModule',
    ])).toEqual([])
  })

  it('allows historical chapter reference fields only in the read-only migration boundary and its test', () => {
    expect(tokenOffenders(
      ['moduleId', "kind: 'module'", 'kind: "module"'],
      ['src/data/legacyChapterReferences.js', 'tests/unit/data/legacyChapterReferences.test.js'],
    )).toEqual([])
  })

  it('keeps canonical chapter source, loader and recovery map as the only authoring surfaces', () => {
    expect(tokenOffenders(['src/modules.js', 'moduleContentRegistry.js', 'tagModuleMap.js'])).toEqual([])
    const registry = readFileSync(resolve(root, 'docs/components/COMPONENT_REGISTRY.md'), 'utf8')
    expect(registry).toContain('ChapterPlayer')
    expect(registry).toContain('ScreenRenderer')
  })
})
""")

print('Phase 6 vocabulary guard hardened')
