// ─── AQA Maths — Number ────────────────────────────────────────────────────────
//
// Chapters of `maths-aqa-number`, in the order the module references them.
// Ids are preserved verbatim: each one backs a live `gcse_chapter_<id>`
// progress key and is never renamed for tidiness.

export default [
  {
    id: 'math1',
    title: 'Place value and number sense',
    subtitle: 'Ordering numbers, decimals and the number line',
    era: 'Number survival kit',
    icon: '🔢',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math1.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math2',
    title: 'The four operations',
    subtitle: 'Add, subtract, multiply and divide with confidence',
    era: 'Number survival kit',
    icon: '➗',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math2.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math3',
    title: 'Negative numbers without panic',
    subtitle: 'Sign rules, subtracting negatives and ordering on a number line',
    era: 'Number survival kit',
    icon: '➖',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math3.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math4',
    title: 'BIDMAS and calculator control',
    subtitle: 'Order of operations, bracket entry and estimation',
    era: 'Number survival kit',
    icon: '🧮',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math4.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math5',
    title: 'Rounding, estimating and checking',
    subtitle: 'Decimal places, significant figures, error intervals and estimation',
    era: 'Number survival kit',
    icon: '≈',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math5.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math6',
    title: 'Factors, multiples and primes',
    subtitle: 'Prime factorisation, HCF, LCM and factor trees',
    era: 'Number survival kit',
    icon: '🔎',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math6.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math7',
    title: 'Powers, roots and standard form',
    subtitle: 'Indices, roots, powers of 10 and scientific notation',
    era: 'Number survival kit',
    icon: '10ˣ',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math7.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
  {
    id: 'math8',
    title: 'Fractions that actually make sense',
    subtitle: 'Equivalent fractions, simplifying, ordering and fractions of amounts',
    era: 'Number survival kit',
    icon: '½',
    headerImage: '/images/maths/_shared/numbers.webp',
    status: 'available',
    contentPath: 'src/content/maths/foundations/episodes/math8.js',
    conceptIds: [],
    requirementIds: [],
    estimatedMinutes: null,
  },
]
