// ─── Subject-browser navigation configuration ─────────────────────────────
//
// BUILD-TIME ONLY. Plain serialisable data, with no imports.
//
// A browser entry is one learner-facing destination. It is application
// navigation configuration expressed over canonical curriculum records; it is
// not a seventh curriculum entity and it owns no learner progress.

const NUMBER_RETIREMENT = 'OD-5-A is decided and the printed chapter numbers are intentionally corrected'
const LABEL_RETIREMENT = 'OD-5-B is decided and the Physics card labels are intentionally normalised'

export default [
  {
    id: 'history',
    position: 0,
    label: 'History',
    title: 'Medicine through time',
    description: 'Explore how medicine and ideas have shaped the world.',
    heroImage: '/images/history/_shared/medicine-through-time.webp',
    themeKey: 'History',
    subjectIds: ['history'],
    pathwayIds: ['pearson-edexcel-history-1hi0-medicine-spain-elizabethan-usa'],
    cardMode: 'chapter',
    comingSoon: null,
    sections: [
      {
        id: 'medicine',
        title: 'Medicine through time',
        shortLabel: 'Medicine',
        heroImage: '/images/history/_shared/medicine-through-time.webp',
        comingSoon: false,
        moduleIds: ['history-edexcel-medicine-britain', 'history-edexcel-western-front'],
      },
      {
        id: 'spain-new-world',
        title: 'Spain and the new world',
        shortLabel: 'Spain',
        heroImage: '/images/history/_shared/spain-new-world.webp',
        comingSoon: false,
        moduleIds: ['history-edexcel-spain-new-world'],
      },
      {
        id: 'elizabethan',
        title: 'Elizabethan England',
        shortLabel: 'Elizabethan',
        heroImage: '/images/history/_shared/elizabethan.webp',
        comingSoon: true,
        moduleIds: ['history-edexcel-early-elizabethan'],
      },
      {
        id: 'usa',
        title: 'USA: conflict at home and abroad',
        shortLabel: 'USA',
        heroImage: '/images/history/_shared/usa-conflict.webp',
        comingSoon: false,
        moduleIds: ['history-edexcel-usa-conflict'],
      },
    ],
    displayNumberOverrides: {
      'history-medicine-surgery-anaesthetics': { value: 4, preserves: 'The current browser prints 4 on the sixth Medicine card.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-jenner-vaccination': { value: 6, preserves: 'The current browser prints 6 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-germ-theory': { value: 7, preserves: 'The current browser prints 7 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-great-stink': { value: 8, preserves: 'The current browser prints 8 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-surgery-revolution': { value: 9, preserves: 'The current browser prints 9 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-nightingale': { value: 10, preserves: 'The current browser prints 10 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-accidental-miracle': { value: 11, preserves: 'The current browser prints 11 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-modern-medicine': { value: 12, preserves: 'The current browser prints 12 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-cancer': { value: 13, preserves: 'The current browser prints 13 after the duplicated 4.', retireWhen: NUMBER_RETIREMENT },
      'history-medicine-western-front': { value: 14, preserves: 'The Western Front is the fifteenth card but currently prints 14.', retireWhen: NUMBER_RETIREMENT },
    },
    cardLabelOverrides: {},
  },
  {
    id: 'biology',
    position: 1,
    label: 'Biology',
    title: 'AQA Biology',
    description: 'Build your understanding from cells to ecosystems.',
    heroImage: '/images/biology/_shared/main.png',
    themeKey: 'Biology',
    subjectIds: ['biology'],
    pathwayIds: ['aqa-biology-8461-foundation', 'aqa-biology-8461-higher'],
    cardMode: 'chapter',
    comingSoon: null,
    sections: null,
    displayNumberOverrides: {
      bio_building_life: { value: 2, preserves: 'The current browser prints 2 on both the second and third Biology cards.', retireWhen: NUMBER_RETIREMENT },
      bio_human_machine: { value: 3, preserves: 'The current browser continues numbering after the duplicated 2.', retireWhen: NUMBER_RETIREMENT },
      bio_disease_wars: { value: 4, preserves: 'The current browser continues numbering after the duplicated 2.', retireWhen: NUMBER_RETIREMENT },
      bio_control_systems: { value: 5, preserves: 'The current browser continues numbering after the duplicated 2.', retireWhen: NUMBER_RETIREMENT },
      bio_genetics_evolution: { value: 6, preserves: 'The current browser continues numbering after the duplicated 2.', retireWhen: NUMBER_RETIREMENT },
      bio_ecosystems_group: { value: 7, preserves: 'The eighth Biology card currently prints 7.', retireWhen: NUMBER_RETIREMENT },
    },
    cardLabelOverrides: {},
  },
  {
    id: 'chemistry',
    position: 2,
    label: 'Chemistry',
    title: 'AQA Chemistry',
    description: 'Master the reactions and patterns behind matter.',
    heroImage: '/images/chemistry/_shared/matteratoms.webp',
    themeKey: 'Chemistry',
    subjectIds: ['chemistry'],
    pathwayIds: ['aqa-chemistry-8462-foundation', 'aqa-chemistry-8462-higher'],
    cardMode: 'none',
    comingSoon: {
      title: 'Content coming soon',
      subtitle: 'Chemistry',
    },
    sections: null,
    displayNumberOverrides: {},
    cardLabelOverrides: {},
  },
  {
    id: 'physics',
    position: 3,
    label: 'Physics',
    title: 'AQA Physics',
    description: 'Explore the forces and energy that shape our world.',
    heroImage: '/images/physics/_shared/forces.webp',
    themeKey: 'Physics',
    subjectIds: ['physics'],
    pathwayIds: ['aqa-physics-8463-foundation', 'aqa-physics-8463-higher'],
    // The current browser order is a navigation decision rather than the
    // specification pathway order. Listing the same canonical module set here
    // preserves that order without inventing any module relationship.
    moduleIds: [
      'physics-aqa-forces-motion',
      'physics-aqa-energy',
      'physics-aqa-waves-electricity',
      'physics-aqa-space',
      'physics-aqa-matter-particles',
    ],
    cardMode: 'module',
    comingSoon: null,
    sections: null,
    displayNumberOverrides: {},
    cardLabelOverrides: {
      'physics-aqa-forces-motion': { value: 'Forces & Motion', preserves: 'The current placeholder uses an ampersand and title case.', retireWhen: LABEL_RETIREMENT },
      'physics-aqa-waves-electricity': { value: 'Waves & Electricity', preserves: 'The current placeholder uses an ampersand and title case.', retireWhen: LABEL_RETIREMENT },
      'physics-aqa-matter-particles': { value: 'Matter & Particles', preserves: 'The current placeholder uses an ampersand and title case.', retireWhen: LABEL_RETIREMENT },
    },
  },
  {
    id: 'maths',
    position: 4,
    label: 'Maths',
    title: 'AQA Mathematics',
    description: 'Build number, algebra and problem-solving fluency.',
    heroImage: '/images/maths/_shared/numbers.webp',
    themeKey: 'Maths',
    subjectIds: ['mathematics'],
    pathwayIds: ['aqa-maths-8300-foundation'],
    cardMode: 'chapter',
    comingSoon: null,
    sections: null,
    displayNumberOverrides: {},
    cardLabelOverrides: {},
  },
  {
    id: 'english',
    position: 5,
    label: 'English',
    title: 'AQA English',
    description: 'Sharpen your reading, analysis and writing skills.',
    heroImage: '/images/english/_shared/macbeth.webp',
    themeKey: 'English',
    subjectIds: ['english-literature'],
    pathwayIds: ['aqa-english-literature-8702-macbeth-inspector'],
    cardMode: 'chapter',
    comingSoon: null,
    sections: [
      {
        id: 'macbeth',
        title: 'Macbeth',
        shortLabel: 'Macbeth',
        // Deliberately reproduces the current wrong image. OD-5-C owns fixing it.
        heroImage: '/images/history/_shared/medicine-through-time.webp',
        comingSoon: false,
        moduleIds: ['english-lit-aqa-macbeth'],
      },
      {
        id: 'inspector',
        title: 'An Inspector Calls',
        shortLabel: 'Inspector',
        // Deliberately reproduces the current wrong image. OD-5-C owns fixing it.
        heroImage: '/images/sociology/_shared/family.webp',
        comingSoon: true,
        moduleIds: ['english-lit-aqa-inspector-calls'],
      },
    ],
    displayNumberOverrides: {},
    cardLabelOverrides: {},
  },
  {
    id: 'sociology',
    position: 6,
    label: 'Sociology',
    title: 'AQA Sociology',
    description: 'Understand the social forces that shape our lives.',
    heroImage: '/images/sociology/_shared/family.webp',
    themeKey: 'Sociology',
    subjectIds: ['sociology'],
    pathwayIds: ['aqa-sociology-8192'],
    cardMode: 'chapter',
    comingSoon: null,
    sections: null,
    displayNumberOverrides: {
      soc6: { value: 6, preserves: 'The current browser skips 5 and prints 6 on the fifth Sociology card.', retireWhen: NUMBER_RETIREMENT },
    },
    cardLabelOverrides: {},
  },
]
