// Figure paths — served from public/figures/
export const FIGURES = {
  'nov20_breathing':               '/figures/nov20_breathing.webp',
  'nov20_temp_graph':              '/figures/nov20_temp_graph.webp',
  'nov20_leaf_experiment':         '/figures/nov20_leaf_experiment.webp',
  'nov20_villi':                   '/figures/nov20_villi.webp',
  'jun22_digestive':               '/figures/jun22_digestive.webp',
  'jun22_leaf_section':            '/figures/jun22_leaf_section.webp',
  'jun22_photosynthesis_apparatus':'/figures/jun22_photosynthesis_apparatus.webp',
  'jun23_cell_oxygen':             '/figures/jun23_cell_oxygen.webp',
  'jun23_transpiration_apparatus': '/figures/jun23_transpiration_apparatus.webp',
  'jun23_heart':                   '/figures/jun23_heart.webp',
  'jun23_breathing':               '/figures/jun23_breathing.webp',
  'jun24_animal_cell':             '/figures/jun24_animal_cell.webp',
  'jun24_cell_magnification':      '/figures/jun24_cell_magnification.webp',
  'jun24_fan_table':               '/figures/jun24_fan_table.webp',
  'jun24_greenhouses':             '/figures/jun24_greenhouses.webp',
  'jun24_osmosis_tube':            '/figures/jun24_osmosis_tube.webp',
  'jun22_cell_cycle':              '/figures/jun22_cell_cycle.webp',
};
