// Figure paths — served from public/figures/
export const FIGURES = {
  'nov20_breathing':               '/images/biology/exam-papers/nov20-breathing.webp',
  'nov20_temp_graph':              '/images/biology/exam-papers/nov20-temp-graph.webp',
  'nov20_leaf_experiment':         '/images/biology/exam-papers/nov20-leaf-experiment.webp',
  'nov20_villi':                   '/images/biology/exam-papers/nov20-villi.webp',
  'jun22_digestive':               '/images/biology/exam-papers/jun22-digestive.webp',
  'jun22_leaf_section':            '/images/biology/exam-papers/jun22-leaf-section.webp',
  'jun22_photosynthesis_apparatus':'/images/biology/exam-papers/jun22-photosynthesis-apparatus.webp',
  'jun23_cell_oxygen':             '/images/biology/exam-papers/jun23-cell-oxygen.webp',
  'jun23_transpiration_apparatus': '/images/biology/exam-papers/jun23-transpiration-apparatus.webp',
  'jun23_heart':                   '/images/biology/exam-papers/jun23-heart.webp',
  'jun23_breathing':               '/images/biology/exam-papers/jun23-breathing.webp',
  'jun24_animal_cell':             '/images/biology/exam-papers/jun24-animal-cell.webp',
  'jun24_cell_magnification':      '/images/biology/exam-papers/jun24-cell-magnification.webp',
  'jun24_fan_table':               '/images/biology/exam-papers/jun24-fan-table.webp',
  'jun24_greenhouses':             '/images/biology/exam-papers/jun24-greenhouses.webp',
  'jun24_osmosis_tube':            '/images/biology/exam-papers/jun24-osmosis-tube.webp',
  'jun22_cell_cycle':              '/images/biology/exam-papers/jun22-cell-cycle.webp',
};
