// Figure paths — served from public/figures/
export const FIGURES = {
  'nov20_breathing':               '/figures/nov20_breathing.png',
  'nov20_temp_graph':              '/figures/nov20_temp_graph.png',
  'nov20_leaf_experiment':         '/figures/nov20_leaf_experiment.png',
  'nov20_villi':                   '/figures/nov20_villi.png',
  'jun22_digestive':               '/figures/jun22_digestive.png',
  'jun22_leaf_section':            '/figures/jun22_leaf_section.png',
  'jun22_photosynthesis_apparatus':'/figures/jun22_photosynthesis_apparatus.png',
  'jun23_cell_oxygen':             '/figures/jun23_cell_oxygen.png',
  'jun23_transpiration_apparatus': '/figures/jun23_transpiration_apparatus.png',
  'jun23_heart':                   '/figures/jun23_heart.png',
  'jun23_breathing':               '/figures/jun23_breathing.png',
  'jun24_animal_cell':             '/figures/jun24_animal_cell.png',
  'jun24_cell_magnification':      '/figures/jun24_cell_magnification.png',
  'jun24_fan_table':               '/figures/jun24_fan_table.png',
  'jun24_greenhouses':             '/figures/jun24_greenhouses.png',
  'jun24_osmosis_tube':            '/figures/jun24_osmosis_tube.png',
  'jun22_cell_cycle':              '/figures/jun22_cell_cycle.png',
};
