// ─── Module metadata ────────────────────────────────────────────────────────
// Lightweight metadata for all modules — used for browsing, cards, progress %,
// and weak-spot routing. Full lesson content (hook, outcomes, screens, intro,
// recall) lives in src/modules/<subject>.js, loaded on demand when a module is
// opened (see openModulePlayer in App.jsx).
//
// screenCount  — number of screens in the full module (was screens.length)
// screenTags   — screen.tag per screen, in order, or null — used by
//                findTaggedScreen() to jump to a specific weak-spot screen
//                without loading the full module content.

export const MODULES = [

  // ── History: Medicine Through Time ──────────────────────────────────────

  {
    id: "history-medicine-medieval-beliefs-causes",
    subject: "History",
    series: "medicine",
    number: 1,
    title: "Trust me, I'm Following Jupiter",
    subtitle: "Medieval medicine: beliefs and causes of disease",
    era: "c.1250–c.1500",
    icon: "⚕️",
    color: "#F5B700",
    colorLight: "#f5e6d3",
    headerImage: "/headers/history-medicine-medieval-beliefs-causes.png",
    screenCount: 32,
    screenTags: [
      null, null, null, "four-humours", null, null, null, "galen", null, null, null,
      "medieval-practitioners", "miasma", null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null, null, "core-takeaway", null,
    ],
  },
  {
    id: "history-medicine-black-death",
    subject: "History",
    series: "medicine",
    number: 2,
    title: "The day everything changed",
    subtitle: "The Black Death, 1348–1349",
    era: "c.1348–c.1350",
    icon: "☠️",
    color: "#8C3A2A",
    colorLight: "rgba(140,58,42,0.12)",
    headerImage: "/headers/history-medicine-black-death.png",
    screenCount: 27,
    screenTags: [
      null, null, null, null, null, null, null, null, "plague-explanations",
      null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "mod2",
    subject: "History",
    series: "medicine",
    number: 3,
    title: "The beginning of doubt",
    subtitle: "Medical Renaissance",
    era: "c.1500–c.1600",
    icon: "🔬",
    color: "#D4950A",
    colorLight: "rgba(212,149,10,.12)",
    headerImage: "/headers/history-medicine-renaissance.png",
    screenCount: 16,
    screenTags: [
      null, null, null, null, "vesalius", null, null, null,
      null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "mod3",
    subject: "History",
    series: "medicine",
    number: 4,
    title: "The man who proved everyone wrong",
    subtitle: "William Harvey and the circulation of blood",
    era: "c.1628",
    icon: "🩺",
    color: "#C47828",
    colorLight: "rgba(196,120,40,.12)",
    headerImage: "/headers/history-medicine-man-proved-wrong.png",
    screenCount: 11,
    screenTags: [
      null, "anaesthetics", null, null, null, null, null, null, "antiseptic-surgery", null, null,
    ],
  },
  {
    id: "history-medicine-great-plague",
    subject: "History",
    series: "medicine",
    number: 5,
    title: "London's year of terror",
    subtitle: "The Great Plague of London",
    era: "c.1665",
    icon: "💀",
    color: "#9A4820",
    colorLight: "rgba(154,72,32,.12)",
    headerImage: "/headers/history-medicine-london-terror.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "history-medicine-jenner-vaccination",
    subject: "History",
    series: "medicine",
    number: 6,
    title: "The boy, the cow and the cure",
    subtitle: "Edward Jenner and the birth of vaccination",
    era: "c.1796–c.1853",
    icon: "🐄",
    color: "#BD7224",
    colorLight: "rgba(189,114,36,.12)",
    headerImage: "/headers/history-medicine-jenner.png",
    screenCount: 1,
    screenTags: [
      "vaccination",
    ],
  },
  {
    id: "history-medicine-germ-theory",
    subject: "History",
    series: "medicine",
    number: 7,
    title: "The invisible enemy",
    subtitle: "Pasteur, Koch and germ theory",
    era: "c.1857–c.1883",
    icon: "🦠",
    color: "#B06520",
    colorLight: "rgba(176,101,32,.12)",
    headerImage: "/headers/history-medicine-invisible-enemy.png",
    screenCount: 10,
    screenTags: [
      "germ-theory", "pasteur", "koch", null, null, null, null, null, "factor-web", null,
    ],
  },
  {
    id: "mod5",
    subject: "History",
    series: "medicine",
    number: 8,
    title: "The great stink",
    subtitle: "Public health 1800–1900",
    era: "c.1800–c.1900",
    icon: "🏭",
    color: "#9A5A18",
    colorLight: "rgba(154,90,24,.12)",
    headerImage: "/headers/history-medicine-great-stink.png",
    screenCount: 7,
    screenTags: [
      null, null, null, "john-snow", "public-health", null, null,
    ],
  },
  {
    id: "mod6",
    subject: "History",
    series: "medicine",
    number: 9,
    title: "The day surgery changed forever",
    subtitle: "Anaesthetics and antiseptics",
    era: "c.1840–c.1900",
    icon: "🔪",
    color: "#7A4515",
    colorLight: "rgba(122,69,21,.12)",
    headerImage: "/headers/history-medicine-surgery-revolution.png",
    screenCount: 10,
    screenTags: [
      null, null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "history-medicine-nightingale",
    subject: "History",
    series: "medicine",
    number: 10,
    title: "The lady with the lamp",
    subtitle: "Florence Nightingale and modern nursing",
    era: "c.1854–c.1860",
    icon: "🕯️",
    color: "#8B5014",
    colorLight: "rgba(139,80,20,.12)",
    headerImage: "/headers/history-medicine-lady-lamp.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "mod7",
    subject: "History",
    series: "medicine",
    number: 11,
    title: "The accidental miracle",
    subtitle: "Magic bullets, penicillin & the antibiotic revolution",
    era: "c.1890–c.1945",
    icon: "💊",
    color: "#7A4515",
    colorLight: "rgba(122,69,21,.12)",
    headerImage: "/headers/history-medicine-accidental-miracle.png",
    screenCount: 11,
    screenTags: [
      null, "magic-bullet", "penicillin", null, null, "wwi-medicine", null, null, null, null, null,
    ],
  },
  {
    id: "mod8",
    subject: "History",
    series: "medicine",
    number: 12,
    title: "When medicine became magic",
    subtitle: "NHS & modern medicine",
    era: "c.1948–present",
    icon: "🧬",
    color: "#1A5276",
    colorLight: "rgba(26,82,118,.12)",
    headerImage: "/headers/history-medicine-modern.png",
    screenCount: 9,
    screenTags: [
      null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "mod9",
    subject: "History",
    series: "medicine",
    number: 13,
    title: "Can we beat cancer?",
    subtitle: "Lung cancer and modern public health",
    era: "AQA GCSE",
    icon: "🏥",
    color: "#C47828",
    colorLight: "rgba(196,120,40,.12)",
    headerImage: "/headers/history-medicine-nhs.png",
    screenCount: 11,
    screenTags: [
      null, null, null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "history-medicine-western-front",
    subject: "History",
    series: "medicine",
    number: 14,
    title: "Hell in the trenches",
    subtitle: "Medicine on the Western Front",
    era: "c.1914–c.1918",
    icon: "⚔️",
    color: "#5A6A4A",
    colorLight: "rgba(90,106,74,.12)",
    headerImage: "/headers/history-medicine-trenches.png",
    screenCount: 19,
    screenTags: [
      "prior-knowledge-western-front",
      "western-front-context",
      "trench-conditions",
      "trench-conditions-recall",
      "chain-of-evacuation",
      "chain-of-evacuation-recall",
      "medical-developments",
      "thomas-splint",
      "blood-transfusions",
      "medical-developments-recall",
      "source-utility",
      "source-follow-up",
      "western-front-core-recall",
      "describe-two-features",
      "describe-two-features",
      "source-utility-exam",
      "source-utility-exam",
      "source-follow-up",
      null,
    ],
  },

  // ── History: Spain & the New World ──────────────────────────────────────

  {
    id: "spain-new-world-1",
    subject: "History",
    series: "spain-new-world",
    number: 1,
    title: "The man who wanted to sail west",
    subtitle: "Spain c.1490, Columbus, Isabella & the 1492 voyage",
    era: "c.1490–c.1492",
    icon: "⛵",
    color: "#C8741C",
    colorLight: "rgba(200,116,28,.12)",
    headerImage: "/headers/spain-man-sail-west.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-2",
    subject: "History",
    series: "spain-new-world",
    number: 2,
    title: "A new world",
    subtitle: "Bahamas, Caribbean, Tainos, Caribs, La Navidad — first encounters",
    era: "c.1492–c.1493",
    icon: "🌍",
    color: "#C07018",
    colorLight: "rgba(192,112,24,.12)",
    headerImage: "/headers/spain-a-new-world.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-3",
    subject: "History",
    series: "spain-new-world",
    number: 3,
    title: "Gold, God and empire",
    subtitle: "Santo Domingo, settlement, disease, missionaries & Treaty of Tordesillas",
    era: "c.1493–c.1500",
    icon: "✝️",
    color: "#B86A14",
    colorLight: "rgba(184,106,20,.12)",
    headerImage: "/headers/spain-gold-god-empire.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-4",
    subject: "History",
    series: "spain-new-world",
    number: 4,
    title: "The Conquistadors",
    subtitle: "Balboa, Cuba, Magellan, the Pacific & Philippines",
    era: "c.1500–c.1521",
    icon: "⚔️",
    color: "#B06410",
    colorLight: "rgba(176,100,16,.12)",
    headerImage: "/headers/spain-conquistadors.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-5",
    subject: "History",
    series: "spain-new-world",
    number: 5,
    title: "The fall of the Aztecs",
    subtitle: "Cortés, Montezuma, Tlaxcalans & Tenochtitlan",
    era: "c.1519–c.1521",
    icon: "🏯",
    color: "#A85E0C",
    colorLight: "rgba(168,94,12,.12)",
    headerImage: "/headers/spain-fall-aztecs.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-6",
    subject: "History",
    series: "spain-new-world",
    number: 6,
    title: "What the Spanish left behind",
    subtitle: "Cortés as governor, consequences for the Aztecs & Panama",
    era: "c.1521–c.1530",
    icon: "💀",
    color: "#A05808",
    colorLight: "rgba(160,88,8,.12)",
    headerImage: "/headers/spain-left-behind.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-7",
    subject: "History",
    series: "spain-new-world",
    number: 7,
    title: "The last Inca Emperor",
    subtitle: "Huayna Capac, Atahuallpa, Huascar & Pizarro",
    era: "c.1527–c.1532",
    icon: "👑",
    color: "#985204",
    colorLight: "rgba(152,82,4,.12)",
    headerImage: "/headers/spain-last-inca.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-8",
    subject: "History",
    series: "spain-new-world",
    number: 8,
    title: "The conquest of Peru",
    subtitle: "Cajamarca, capture, revolt & the siege of Cuzco",
    era: "c.1532–c.1536",
    icon: "⚔️",
    color: "#8A4C00",
    colorLight: "rgba(138,76,0,.12)",
    headerImage: "/headers/spain-conquest-peru.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-9",
    subject: "History",
    series: "spain-new-world",
    number: 9,
    title: "How to rule an empire",
    subtitle: "Viceroys, encomienda, Las Casas & the New Laws",
    era: "c.1535–c.1550",
    icon: "🏛️",
    color: "#824600",
    colorLight: "rgba(130,70,0,.12)",
    headerImage: "/headers/spain-rule-empire.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "spain-new-world-10",
    subject: "History",
    series: "spain-new-world",
    number: 10,
    title: "Silver changed everything",
    subtitle: "Bolivia, Mexico, La Paz, economy, House of Trade & Council of the Indies",
    era: "c.1545–c.1600",
    icon: "💰",
    color: "#7A4000",
    colorLight: "rgba(122,64,0,.12)",
    headerImage: "/headers/spain-silver-changed.png",
    screenCount: 0,
    screenTags: [],
  },

  // ── History: USA — Conflict at Home & Abroad ────────────────────────────

  {
    id: "usa-segregation",
    subject: "History",
    series: "usa",
    number: 1,
    title: "Separate and unequal",
    subtitle: "Segregation, discrimination, NAACP & CORE",
    era: "c.1865–c.1954",
    icon: "✊",
    color: "#B82020",
    colorLight: "rgba(184,32,32,.12)",
    headerImage: "/headers/usa-separate-unequal.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-brown-v-board",
    subject: "History",
    series: "usa",
    number: 2,
    title: "The girl who walked into history",
    subtitle: "Brown v Board of Education & Little Rock",
    era: "c.1954–c.1957",
    icon: "🏫",
    color: "#B02222",
    colorLight: "rgba(176,34,34,.12)",
    headerImage: "/headers/usa-girl-walked-history.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-rosa-parks",
    subject: "History",
    series: "usa",
    number: 3,
    title: "The woman who stayed seated",
    subtitle: "Rosa Parks, Montgomery, MLK, SCLC & Civil Rights Act 1957",
    era: "c.1955–c.1957",
    icon: "🚌",
    color: "#A82424",
    colorLight: "rgba(168,36,36,.12)",
    headerImage: "/headers/usa-woman-stayed-seated.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-sit-ins",
    subject: "History",
    series: "usa",
    number: 4,
    title: "Standing up, sitting down",
    subtitle: "Sit-ins, Freedom Riders & James Meredith",
    era: "c.1960–c.1962",
    icon: "🪑",
    color: "#A02626",
    colorLight: "rgba(160,38,38,.12)",
    headerImage: "/headers/usa-standing-sitting.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-i-have-a-dream",
    subject: "History",
    series: "usa",
    number: 5,
    title: "I have a dream",
    subtitle: "Birmingham, Washington, Freedom Summer, Civil Rights Act 1964, Selma & Voting Rights Act",
    era: "c.1963–c.1965",
    icon: "🕊️",
    color: "#982828",
    colorLight: "rgba(152,40,40,.12)",
    headerImage: "/headers/usa-i-have-a-dream.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-malcolm-x",
    subject: "History",
    series: "usa",
    number: 6,
    title: "By any means necessary",
    subtitle: "Malcolm X, Black Muslims, Black Power, Carmichael, Mexico Olympics & Black Panthers",
    era: "c.1960–c.1969",
    icon: "✊",
    color: "#902A2A",
    colorLight: "rgba(144,42,42,.12)",
    headerImage: "/headers/usa-by-any-means.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-how-much-changed",
    subject: "History",
    series: "usa",
    number: 7,
    title: "How much had really changed?",
    subtitle: "Riots, Kerner Report, King's later campaigns, assassination & extent of progress by 1975",
    era: "c.1965–c.1975",
    icon: "⚖️",
    color: "#882C2C",
    colorLight: "rgba(136,44,44,.12)",
    headerImage: "/headers/usa-how-much-changed.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-why-vietnam",
    subject: "History",
    series: "usa",
    number: 8,
    title: "Why America went to Vietnam",
    subtitle: "Domino Theory, Eisenhower, Kennedy & Diem",
    era: "c.1945–c.1963",
    icon: "🗺️",
    color: "#2A4A6A",
    colorLight: "rgba(42,74,106,.12)",
    headerImage: "/headers/usa-why-vietnam.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-americas-war",
    subject: "History",
    series: "usa",
    number: 9,
    title: "America's war",
    subtitle: "Johnson, Gulf of Tonkin, escalation, Vietcong tactics, Search and Destroy, Rolling Thunder & Tet",
    era: "c.1964–c.1968",
    icon: "🔥",
    color: "#264468",
    colorLight: "rgba(38,68,104,.12)",
    headerImage: "/headers/usa-americas-war.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-guerrilla-war",
    subject: "History",
    series: "usa",
    number: 10,
    title: "Can you win a guerrilla war?",
    subtitle: "Vietnamisation, Nixon, Cambodia, Laos & bombing campaigns",
    era: "c.1969–c.1972",
    icon: "🌴",
    color: "#223E66",
    colorLight: "rgba(34,62,102,.12)",
    headerImage: "/headers/usa-guerrilla-war.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-war-comes-home",
    subject: "History",
    series: "usa",
    number: 11,
    title: "The war comes home",
    subtitle: "Student protests, TV coverage, draft, My Lai, Kent State, silent majority & hard hats",
    era: "c.1968–c.1973",
    icon: "📺",
    color: "#1E3864",
    colorLight: "rgba(30,56,100,.12)",
    headerImage: "/headers/usa-war-comes-home.png",
    screenCount: 0,
    screenTags: [],
  },
  {
    id: "usa-long-way-out",
    subject: "History",
    series: "usa",
    number: 12,
    title: "The long way out",
    subtitle: "Paris Peace Agreement, withdrawal, why the USA failed, Ho Chi Minh Trail, costs of the war",
    era: "c.1973–c.1975",
    icon: "🕊️",
    color: "#1A3262",
    colorLight: "rgba(26,50,98,.12)",
    headerImage: "/headers/usa-long-way-out.png",
    screenCount: 0,
    screenTags: [],
  },

  // ── Biology ──────────────────────────────────────────────────────────────

  {
    id: "bio_building_blocks",
    subject: "Biology",
    number: 1,
    title: "Building blocks",
    subtitle: "What every living thing is built from",
    era: null,
    icon: "🧬",
    color: "#4FA36C",
    colorLight: "rgba(79,163,108,.15)",
    headerImage: "/headers/bio-main.webp",
    screenCount: 13,
    screenTags: [
      null, null, null, null, null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "sci_bio_w1",
    subject: "Biology",
    number: 2,
    title: "Plant Cells & Photosynthesis",
    subtitle: "Tiny factories, big chemistry",
    era: null,
    icon: "🌿",
    color: "#38D27A",
    colorLight: "rgba(56,210,122,.15)",
    headerImage: "/headers/bio-buildinglife.webp",
    screenCount: 9,
    screenTags: [
      null, null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "bio_building_life",
    subject: "Biology",
    number: 2,
    title: "Building Life",
    subtitle: "Cells, Microscopes & Division",
    era: null,
    icon: "🔬",
    color: "#65E6C6",
    colorLight: "rgba(101,230,198,.15)",
    headerImage: "/headers/bio-buildinglife.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "bio_human_machine",
    subject: "Biology",
    number: 3,
    title: "The Human Machine",
    subtitle: "Organs, Digestion & Circulation",
    era: null,
    icon: "🫀",
    color: "#E87B5F",
    colorLight: "rgba(232,123,95,.15)",
    headerImage: "/headers/bio-humanmachine.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "bio_disease_wars",
    subject: "Biology",
    number: 4,
    title: "Disease Wars",
    subtitle: "Pathogens, Immunity & Treatment",
    era: null,
    icon: "🦠",
    color: "#E84F6B",
    colorLight: "rgba(232,79,107,.15)",
    headerImage: "/headers/bio-diseasewars.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "bio_control_systems",
    subject: "Biology",
    number: 5,
    title: "Control Systems",
    subtitle: "Nerves, Hormones & Reproduction",
    era: null,
    icon: "🧠",
    color: "#9B8BE8",
    colorLight: "rgba(155,139,232,.15)",
    headerImage: "/headers/bio-controlsystems.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "bio_genetics_evolution",
    subject: "Biology",
    number: 6,
    title: "Genetics & Evolution",
    subtitle: "DNA, Inheritance & Natural Selection",
    era: null,
    icon: "🧬",
    color: "#7EC8E3",
    colorLight: "rgba(126,200,227,.15)",
    headerImage: "/headers/bio-genetics.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "bio_ecosystems_group",
    subject: "Biology",
    number: 7,
    title: "Ecosystems",
    subtitle: "Food Chains, Biodiversity & Conservation",
    era: null,
    icon: "🌿",
    color: "#68C18A",
    colorLight: "rgba(104,193,138,.15)",
    headerImage: "/headers/bio-ecosystems.webp",
    screenCount: 1,
    screenTags: [null],
  },

  // ── Maths ────────────────────────────────────────────────────────────────

  {
    id: "math1",
    subject: "Maths",
    number: 1,
    title: "Maths Survival Basics",
    subtitle: "Number sense, negatives, BIDMAS",
    era: "Foundation",
    icon: "🔢",
    color: "#4B90FF",
    colorLight: "rgba(75,144,255,.12)",
    headerImage: "/headers/maths-numbers.webp",
    screenCount: 8,
    screenTags: [null, null, null, null, null, null, null, null],
  },
  {
    id: "math2",
    subject: "Maths",
    number: 2,
    title: "Fraction Foundations",
    subtitle: "Numerator, denominator, equivalent fractions",
    era: "Foundation",
    icon: "🍕",
    color: "#4B90FF",
    colorLight: "rgba(75,144,255,.12)",
    headerImage: "/headers/maths-numbers.webp",
    screenCount: 9,
    screenTags: [null, null, null, null, null, null, null, null, null],
  },

  // ── Sociology ────────────────────────────────────────────────────────────

  {
    id: "soc1",
    subject: "Sociology",
    number: 1,
    title: "What Even is Sociology?",
    subtitle: "Culture, norms, values and socialisation",
    era: "AQA GCSE",
    icon: "👥",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-main.webp",
    screenCount: 12,
    screenTags: [null, null, null, null, null, null, null, null, null, null, null, null],
  },
  {
    id: "soc2",
    subject: "Sociology",
    number: 2,
    title: "Marxism vs Functionalism",
    subtitle: "Why does society work — conflict or cooperation?",
    era: "AQA GCSE",
    icon: "⚔️",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-main.webp",
    screenCount: 17,
    screenTags: [
      null, null, null, null, null, null, null, null, null,
      null, null, null, null, null, null, null, null,
    ],
  },
  {
    id: "soc3",
    subject: "Sociology",
    number: 3,
    title: "Feminism, Power & Life Chances",
    subtitle: "Who has power — and who gets left behind?",
    era: "AQA GCSE",
    icon: "⚖️",
    color: "#D96030",
    colorLight: "rgba(123,63,140,.12)",
    headerImage: "/headers/sociology-stratification.webp",
    screenCount: 12,
    screenTags: [null, null, null, null, null, null, null, null, null, null, null, null],
  },
  {
    id: "soc4",
    subject: "Sociology",
    number: 4,
    title: "Family & Households",
    subtitle: "Why families are more sociological than you realised.",
    era: "AQA GCSE",
    icon: "🏠",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-family.webp",
    screenCount: 12,
    screenTags: [null, null, null, null, null, null, null, null, null, null, null, null],
  },
  {
    id: "soc6",
    subject: "Sociology",
    number: 6,
    title: "Family Researchers & Theory Battles",
    subtitle: "Who actually understands family life?",
    era: "Core Theory",
    icon: "⚔️",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-family.webp",
    screenCount: 12,
    screenTags: [null, null, null, null, null, null, null, null, null, null, null, null],
  },

  // ── Chemistry ────────────────────────────────────────────────────────────

  {
    id: "chem_matter_atoms",
    subject: "Chemistry",
    number: 1,
    title: "Matter & Atoms",
    subtitle: "Elements, Bonding & Giant Structures",
    era: null,
    icon: "⚛️",
    color: "#9B59E8",
    colorLight: "rgba(155,89,232,.15)",
    headerImage: "/headers/chem-matteratoms.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "chem_reactions",
    subject: "Chemistry",
    number: 2,
    title: "Chemical Reactions",
    subtitle: "Equations, Acids & Electrolysis",
    era: null,
    icon: "🧪",
    color: "#C459E8",
    colorLight: "rgba(196,89,232,.15)",
    headerImage: "/headers/chem-reactions.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "chem_rates_organic",
    subject: "Chemistry",
    number: 3,
    title: "Rates & Organic Chemistry",
    subtitle: "Rates, Equilibria, Hydrocarbons & Fuels",
    era: null,
    icon: "🛢️",
    color: "#8B59E8",
    colorLight: "rgba(139,89,232,.15)",
    headerImage: "/headers/chem-rates.webp",
    screenCount: 1,
    screenTags: [null],
  },
  {
    id: "chem_earth",
    subject: "Chemistry",
    number: 4,
    title: "Earth Chemistry",
    subtitle: "Atmosphere, Climate & Resources",
    era: null,
    icon: "🌍",
    color: "#5980E8",
    colorLight: "rgba(89,128,232,.15)",
    headerImage: "/headers/chem-earth.webp",
    screenCount: 1,
    screenTags: [null],
  },
]
