// ─── Module metadata ────────────────────────────────────────────────────────
// Lightweight metadata for all modules — used for browsing, cards, progress %,
// and weak-spot routing. Full lesson content (hook, outcomes, screens, intro,
// recall) lives in src/modules/<subject>.js, loaded on demand when a module is
// opened (see openModulePlayer in App.jsx).
//
// screenCount  — number of screens in the full module (was screens.length)
// screenTags   — screen.tag per screen, in order, or null — used by
//                findTaggedScreen() to jump to a specific weak-spot screen
//                without loading the full module content.

export const MODULES = [
  {
    id: "history-medicine-medieval-beliefs-causes",
    subject: "History",
    number: 1,
    title: "Trust me, I'm Following Jupiter",
    subtitle: "Medieval Medicine: Beliefs and Causes of Disease",
    era: "c.1250–c.1500",
    icon: "⚕️",
    color: "#F5B700",
    colorLight: "#f5e6d3",
    headerImage: "/headers/history-medicine-medieval-beliefs-causes.png",
    screenCount: 32,
    screenTags: [
      null,
      null,
      null,
      "four-humours",
      null,
      null,
      null,
      "galen",
      null,
      null,
      null,
      "medieval-practitioners",
      "miasma",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "core-takeaway",
      null,
    ],
  },
  {
    id: "history-medicine-black-death",
    subject: "History",
    number: 2,
    title: "The day everything changed",
    subtitle: "The Black Death, 1348–1349",
    era: "c.1348–c.1350",
    icon: "☠️",
    color: "#8C3A2A",
    colorLight: "rgba(140,58,42,0.12)",
    headerImage: "/headers/history-medicine-black-death.png",
    screenCount: 27,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      "plague-explanations",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod2",
    subject: "History",
    number: 3,
    title: "Renaissance & the Plague",
    subtitle: "Challenge & Continuity",
    era: "c1500–c1700",
    icon: "🔬",
    color: "#D4950A",
    colorLight: "rgba(212,149,10,.12)",
    headerImage: "/headers/history-medicine-renaissance.png",
    screenCount: 16,
    screenTags: [
      null,
      null,
      null,
      null,
      "vesalius",
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod3",
    subject: "History",
    number: 4,
    title: "Surgery & anatomy",
    subtitle: "Hold him down and hope",
    era: "c1700–c1900",
    icon: "🩺",
    color: "#C47828",
    colorLight: "rgba(196,120,40,.12)",
    headerImage: "/headers/history-medicine-man-proved-wrong.png",
    screenCount: 11,
    screenTags: [
      null,
      "anaesthetics",
      null,
      null,
      null,
      null,
      null,
      null,
      "antiseptic-surgery",
      null,
      null,
    ],
  },
  {
    id: "history-medicine-jenner-vaccination",
    subject: "History",
    number: 5,
    title: "The boy, the cow and the cure",
    subtitle: "Edward Jenner and the birth of vaccination",
    era: "c.1796–c.1853",
    icon: "🐄",
    color: "#BD7224",
    colorLight: "rgba(189,114,36,.12)",
    headerImage: "/headers/history-medicine-jenner.png",
    screenCount: 1,
    screenTags: [
      "vaccination",
    ],
  },
  {
    id: "history-medicine-germ-theory",
    subject: "History",
    number: 6,
    title: "The invisible enemy",
    subtitle: "Pasteur, Koch and germ theory",
    era: "c1857–c1883",
    icon: "🦠",
    color: "#B06520",
    colorLight: "rgba(176,101,32,.12)",
    headerImage: "/headers/history-medicine-invisible-enemy.png",
    screenCount: 9,
    screenTags: [
      "germ-theory",
      "pasteur",
      "koch",
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod5",
    subject: "History",
    number: 7,
    title: "The Great Stink",
    subtitle: "Cities, sewers & slow progress",
    era: "c1800–c1900",
    icon: "🏭",
    color: "#9A5A18",
    colorLight: "rgba(154,90,24,.12)",
    headerImage: "/headers/history-medicine-great-stink.png",
    screenCount: 7,
    screenTags: [
      null,
      null,
      null,
      "john-snow",
      "public-health",
      null,
      null,
    ],
  },
  {
    id: "mod6",
    subject: "History",
    number: 8,
    title: "The surgery revolution",
    subtitle: "Pain, infection & survival (1840–1900)",
    era: "c1840–c1900",
    icon: "🔪",
    color: "#7A4515",
    colorLight: "rgba(122,69,21,.12)",
    headerImage: "/headers/history-medicine-surgery-revolution.png",
    screenCount: 10,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod7",
    subject: "History",
    number: 9,
    title: "The accidental miracle",
    subtitle: "Magic bullets, penicillin & the antibiotic revolution",
    era: "c1890–c1945",
    icon: "💊",
    color: "#7A4515",
    colorLight: "rgba(122,69,21,.12)",
    headerImage: "/headers/history-medicine-accidental-miracle.png",
    screenCount: 11,
    screenTags: [
      null,
      "magic-bullet",
      "penicillin",
      null,
      null,
      "wwi-medicine",
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod8",
    subject: "History",
    number: 10,
    title: "Inside modern medicine",
    subtitle: "Scans, transplants, DNA & the future",
    era: "c1945–present",
    icon: "🧬",
    color: "#1A5276",
    colorLight: "rgba(26,82,118,.12)",
    headerImage: "/headers/history-medicine-modern.png",
    screenCount: 9,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "bio_building_blocks",
    subject: "Biology",
    number: 1,
    title: "Building blocks",
    subtitle: "What every living thing is built from",
    era: null,
    icon: "🧬",
    color: "#4FA36C",
    colorLight: "rgba(79,163,108,.15)",
    headerImage: "/headers/bio-main.webp",
    screenCount: 13,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "sci_bio_w1",
    subject: "Biology",
    number: 2,
    title: "Plant Cells & Photosynthesis",
    subtitle: "Tiny factories, big chemistry",
    era: null,
    icon: "🌿",
    color: "#38D27A",
    colorLight: "rgba(56,210,122,.15)",
    headerImage: "/headers/bio-buildinglife.webp",
    screenCount: 9,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "math1",
    subject: "Maths",
    number: 1,
    title: "Maths Survival Basics",
    subtitle: "Number sense, negatives, BIDMAS",
    era: "Foundation",
    icon: "🔢",
    color: "#4B90FF",
    colorLight: "rgba(75,144,255,.12)",
    headerImage: "/headers/maths-numbers.webp",
    screenCount: 8,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "math2",
    subject: "Maths",
    number: 2,
    title: "Fraction Foundations",
    subtitle: "Numerator, denominator, equivalent fractions",
    era: "Foundation",
    icon: "🍕",
    color: "#4B90FF",
    colorLight: "rgba(75,144,255,.12)",
    headerImage: "/headers/maths-numbers.webp",
    screenCount: 9,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "soc1",
    subject: "Sociology",
    number: 1,
    title: "What Even is Sociology?",
    subtitle: "Culture, norms, values and socialisation",
    era: "AQA GCSE",
    icon: "👥",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-main.webp",
    screenCount: 12,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "soc2",
    subject: "Sociology",
    number: 2,
    title: "Marxism vs Functionalism",
    subtitle: "Why does society work — conflict or cooperation?",
    era: "AQA GCSE",
    icon: "⚔️",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-main.webp",
    screenCount: 17,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "soc3",
    subject: "Sociology",
    number: 3,
    title: "Feminism, Power & Life Chances",
    subtitle: "Who has power — and who gets left behind?",
    era: "AQA GCSE",
    icon: "⚖️",
    color: "#D96030",
    colorLight: "rgba(123,63,140,.12)",
    headerImage: "/headers/sociology-stratification.webp",
    screenCount: 12,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "soc4",
    subject: "Sociology",
    number: 4,
    title: "Family & Households",
    subtitle: "Why families are more sociological than you realised.",
    era: "AQA GCSE",
    icon: "🏠",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-family.webp",
    screenCount: 12,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "soc6",
    subject: "Sociology",
    number: 6,
    title: "Family Researchers & Theory Battles",
    subtitle: "Who actually understands family life?",
    era: "Core Theory",
    icon: "⚔️",
    color: "#D96030",
    colorLight: "rgba(217,96,48,.12)",
    headerImage: "/headers/sociology-family.webp",
    screenCount: 12,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "mod9",
    subject: "History",
    number: 11,
    title: "Who gets healthcare?",
    subtitle: "The NHS, prevention & modern public health",
    era: "AQA GCSE",
    icon: "🏥",
    color: "#C47828",
    colorLight: "rgba(196,120,40,.12)",
    headerImage: "/headers/history-medicine-nhs.png",
    screenCount: 10,
    screenTags: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ],
  },
  {
    id: "bio_building_life",
    subject: "Biology",
    number: 2,
    title: "Building Life",
    subtitle: "Cells, Microscopes & Division",
    era: null,
    icon: "🔬",
    color: "#65E6C6",
    colorLight: "rgba(101,230,198,.15)",
    headerImage: "/headers/bio-buildinglife.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "bio_human_machine",
    subject: "Biology",
    number: 3,
    title: "The Human Machine",
    subtitle: "Organs, Digestion & Circulation",
    era: null,
    icon: "🫀",
    color: "#E87B5F",
    colorLight: "rgba(232,123,95,.15)",
    headerImage: "/headers/bio-humanmachine.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "bio_disease_wars",
    subject: "Biology",
    number: 4,
    title: "Disease Wars",
    subtitle: "Pathogens, Immunity & Treatment",
    era: null,
    icon: "🦠",
    color: "#E84F6B",
    colorLight: "rgba(232,79,107,.15)",
    headerImage: "/headers/bio-diseasewars.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "bio_control_systems",
    subject: "Biology",
    number: 5,
    title: "Control Systems",
    subtitle: "Nerves, Hormones & Reproduction",
    era: null,
    icon: "🧠",
    color: "#9B8BE8",
    colorLight: "rgba(155,139,232,.15)",
    headerImage: "/headers/bio-controlsystems.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "bio_genetics_evolution",
    subject: "Biology",
    number: 6,
    title: "Genetics & Evolution",
    subtitle: "DNA, Inheritance & Natural Selection",
    era: null,
    icon: "🧬",
    color: "#7EC8E3",
    colorLight: "rgba(126,200,227,.15)",
    headerImage: "/headers/bio-genetics.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "bio_ecosystems_group",
    subject: "Biology",
    number: 7,
    title: "Ecosystems",
    subtitle: "Food Chains, Biodiversity & Conservation",
    era: null,
    icon: "🌿",
    color: "#68C18A",
    colorLight: "rgba(104,193,138,.15)",
    headerImage: "/headers/bio-ecosystems.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "chem_matter_atoms",
    subject: "Chemistry",
    number: 1,
    title: "Matter & Atoms",
    subtitle: "Elements, Bonding & Giant Structures",
    era: null,
    icon: "⚛️",
    color: "#9B59E8",
    colorLight: "rgba(155,89,232,.15)",
    headerImage: "/headers/chem-matteratoms.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "chem_reactions",
    subject: "Chemistry",
    number: 2,
    title: "Chemical Reactions",
    subtitle: "Equations, Acids & Electrolysis",
    era: null,
    icon: "🧪",
    color: "#C459E8",
    colorLight: "rgba(196,89,232,.15)",
    headerImage: "/headers/chem-reactions.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "chem_rates_organic",
    subject: "Chemistry",
    number: 3,
    title: "Rates & Organic Chemistry",
    subtitle: "Rates, Equilibria, Hydrocarbons & Fuels",
    era: null,
    icon: "🛢️",
    color: "#8B59E8",
    colorLight: "rgba(139,89,232,.15)",
    headerImage: "/headers/chem-rates.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
  {
    id: "chem_earth",
    subject: "Chemistry",
    number: 4,
    title: "Earth Chemistry",
    subtitle: "Atmosphere, Climate & Resources",
    era: null,
    icon: "🌍",
    color: "#5980E8",
    colorLight: "rgba(89,128,232,.15)",
    headerImage: "/headers/chem-earth.webp",
    screenCount: 1,
    screenTags: [
      null,
    ],
  },
]
