// AQA GCSE Sociology (8192) Subject Specific Vocabulary — complete term list.
// Sorted longest-first so multi-word phrases match before their component words.

const RAW_TERMS = [
  // Families & Households
  'Privatised instrumentalism', 'Principle of stratified diffusion', 'Domestic division of labour',
  'Functionally important roles', 'Traditional family roles', 'Integrated conjugal roles',
  'Segregated conjugal roles', 'Dependent family members', 'Agency of socialisation',
  'Reconstituted family', 'Blended family', 'Conventional family', 'Dysfunctional families',
  'Dual career family', 'Extended family', 'Empty nest family', 'Lone parent family',
  'Matriarchal family', 'Nuclear family', 'Patriarchal family', 'Privatised nuclear family',
  'Symmetrical family', 'Crisis of masculinity', 'Double standards', 'Serial monogamy',
  'Separate spheres', 'Empty shell marriage', 'Arranged marriage', 'Family diversity',
  'Gender deal', 'Gender roles', 'Value consensus', 'Social stratification', 'Social construct',
  'Social exclusion', 'Social cohesion', 'Social inequality', 'Social mobility', 'Social control',
  'Social change', 'Social stigma', 'Social order', 'Social class', 'Social network',
  'Social conventions', 'Social convention', 'Socially defined behaviour', 'Double shift',
  'Conjugal relationships', 'Conjugal roles', 'Role conflict', 'Ethnic diversity', 'Ethnic minority',
  'Ethnic group', 'Mass media', 'Popular press', 'Quality press', 'Racial discrimination',
  'Universalistic standards', 'Particularistic standards', 'Secondary socialisation',
  'Primary socialisation', 'Child rearing', 'Welfare state', 'Work life balance',
  'Technological change', 'Theoretical perspective', 'Working class', 'Middle class',
  'Upper class', 'World view', 'Life chances', 'Life expectancy', 'Male domination',
  'Expressive role', 'Instrumental role', 'Class deal',
  // Education
  'Ethnocentric curriculum', 'Correspondence principle', 'Counter school subculture',
  'Anti-school sub-culture', 'Compulsory state education', 'Cultural deprivation',
  'Cultural capital', 'Cultural values', 'Gendered curriculum', 'Formal curriculum',
  'Hidden curriculum', 'National Curriculum', 'Education reform', 'Marketization of education',
  'Vocationalism in education', 'Setting in education', 'League tables in education',
  'Selective schools', 'Special school', 'Specialist school', 'Free school',
  'Fee paying school', 'Organised religion', 'Teacher expectations', 'Tripartite system',
  'Self-fulfilling prophecy', 'Master status', 'Mixed ability', 'Formal education',
  'Informal education', 'Further education', 'Higher education', 'Public examinations',
  'Home tuition', 'Eleven plus', 'Institutional racism', 'Intelligence quotient',
  'Interest groups', 'Glass ceiling', 'Youth culture', 'News value',
  // Crime & Deviance
  'Deviancy amplification', 'Criminal justice system', 'Criminal subculture', 'Corporate crime',
  'Dark figure of crime', 'Official crime statistics', 'Victim survey', 'Self-report study',
  'Gender and criminality', 'White collar crime', 'Miscarriage of justice',
  'Non-indictable offence', 'Indictable offence', 'Deviant career', 'Moral panic', 'Folk devils',
  'Media amplification', 'Media stereotype', 'Agenda setting', 'Agent of social control',
  'Anti-social behaviour', 'Chivalry thesis', 'Community service', 'Control theory',
  'Crime rate', 'Identity theft', 'Legislative process', 'Police caution', 'Prison system',
  'Probation system', 'Recorded crime', 'Reported crime', 'Right of appeal', 'Status frustration',
  'Unwritten rules', 'Youth crime',
  // Social Stratification
  'False class consciousness', 'Ruling class ideology', 'Culture of dependency',
  'Cycle of deprivation', 'Relative income standard of poverty', 'State standard of poverty',
  'Environmental poverty', 'Absolute poverty', 'Relative poverty', 'Subjective poverty',
  'Poverty trap', 'Welfare benefits', 'Welfare reform', 'Welfare scrounger', 'Universal benefits',
  'Selective benefits', 'New social movement', 'Political socialisation', 'Political party',
  'Liberal democratic values', 'Legal rational authority', 'Charismatic authority',
  'Traditional authority', 'Bureaucratic authority', 'First past the post',
  'Proportional representation', 'Distribution of power', 'Means of production',
  'Means testing', 'Market situation', 'Class dealignment', 'Class alignment', 'Class struggle',
  'Classless society', 'Petty Bourgeoisie', 'Achieved status', 'Ascribed status', 'Asylum seeker',
  'Subjective class', 'Industrial dispute', 'Left and right wing', 'Member of Parliament',
  'Nation state', 'New Right', 'Direct action', 'Surplus wealth', 'Trade union', 'Under-employment',
  'Lumpenproletariat', 'Embourgeoisement', 'Proletarianism', 'Social security', 'Pressure group',
  'Prime Minister', 'White collar worker', 'Relative deprivation',
  // Research Methods
  'Mixed methods research', 'Non-participant observation', 'Participant observation',
  'Covert observation', 'Longitudinal study', 'Ethical considerations', 'Content analysis',
  'Data analysis', 'Data protection', 'Qualitative data', 'Quantitative data', 'Primary data',
  'Secondary data', 'Selective use of data', 'Representative data', 'Unrepresentative data',
  'Attitude survey', 'Case study', 'Closed question', 'Focus group', 'Informed consent',
  'Open question', 'Quota sample', 'Random sample', 'Sampling frame', 'Snowball sample',
  'Systematic sampling', 'Unstructured interview',
  // Single-word / shorter terms (after multi-word to avoid greedy early match)
  'Adolescence', 'Affluence', 'Ageism', 'Alienation', 'Anomie', 'Aristocracy',
  'Assimilation', 'Authority', 'Bias', 'Bigamy', 'Bourgeois', 'Bourgeoisie',
  'Bureaucracy', 'Canalization', 'Capitalism', 'Capitalist', 'Caste', 'Census',
  'Censorship', 'Childhood', 'Citizenship', 'Cohabitation', 'Commune', 'Communism',
  'Community', 'Conformity', 'Consensus', 'Constituency', 'Continuity', 'Crime',
  'Culture', 'Curriculum', 'Data', 'Deferential', 'Delinquency', 'Deviance',
  'Dictatorship', 'Discrimination', 'Divorce', 'Economy', 'Education', 'Egalitarian',
  'Elite', 'Emigration', 'Employment', 'Ethnicity', 'Ethnography', 'Expectations',
  'Family', 'Fascism', 'Feminism', 'Feminists', 'Feudalism', 'Functionalism',
  'Functionalists', 'Fundamentalism', 'Gender', 'Hypothesis', 'Identity', 'Immigrant',
  'Immigration', 'Income', 'Injustice', 'Interactionism', 'Intergenerational', 'Interview',
  'Isolation', 'Judiciary', 'Kibbutz', 'Kinship', 'Labelling', 'Law', 'Legislation',
  'Lifestyle', 'Magistrate', 'Marriage', 'Marxism', 'Marxist', 'Matriarch', 'Meritocracy',
  'Migration', 'Monarchy', 'Monogamy', 'Multiculturalism', 'Norms', 'Observation',
  'Oligarchy', 'Patriarchy', 'Pluralism', 'Polyandry', 'Polygamy', 'Polygyny',
  'Population', 'Poverty', 'Power', 'Prejudice', 'Propaganda', 'Proletariat',
  'Questionnaire', 'Racism', 'Reliability', 'Research', 'Respondent', 'Roles',
  'Rural', 'Sample', 'Sanctions', 'Scapegoat', 'Secularisation', 'Sexism', 'Slavery',
  'Socialisation', 'Socialism', 'Society', 'Status', 'Stepparent', 'Stereotype',
  'Subculture', 'Survey', 'Surveillance', 'Terrorism', 'Underclass', 'Unemployment',
  'Urban', 'Validity', 'Values', 'Wage', 'Wealth', 'Kin',
]

// Deduplicate and sort longest-first so multi-word phrases match before substrings
const seen = new Set()
export const SOC_KEY_TERMS = RAW_TERMS
  .filter(t => { const k = t.toLowerCase(); if (seen.has(k)) return false; seen.add(k); return true })
  .sort((a, b) => b.length - a.length)
